"""Widen reset_token column and fix workout_sessions.plan_id FK cascade

- users.reset_token: VARCHAR(6) → VARCHAR(64) so that the 43-char
  token_urlsafe(32) generated by forgot_password can actually be stored.
- workout_sessions.plan_id: drop the implicit NO ACTION FK and recreate it
  with ON DELETE SET NULL so that deleting a plan doesn't 500.

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-03
"""

from alembic import op

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("ALTER TABLE users ALTER COLUMN reset_token TYPE VARCHAR(64)")

    op.execute(
        "ALTER TABLE workout_sessions "
        "DROP CONSTRAINT IF EXISTS workout_sessions_plan_id_fkey"
    )
    op.execute(
        "ALTER TABLE workout_sessions "
        "ADD CONSTRAINT workout_sessions_plan_id_fkey "
        "FOREIGN KEY (plan_id) REFERENCES workout_plans(id) ON DELETE SET NULL"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE workout_sessions "
        "DROP CONSTRAINT IF EXISTS workout_sessions_plan_id_fkey"
    )
    op.execute(
        "ALTER TABLE workout_sessions "
        "ADD CONSTRAINT workout_sessions_plan_id_fkey "
        "FOREIGN KEY (plan_id) REFERENCES workout_plans(id)"
    )
    op.execute("ALTER TABLE users ALTER COLUMN reset_token TYPE VARCHAR(6)")
